# Railway配置文件
# https://docs.railway.app/reference/config-file

[build]
builder = "nixpacks"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "3000"

# 以下环境变量需要在Railway控制台中手动设置
# AI_API_KEY = "your-ai-api-key"
# AI_BASE_URL = "https://api-inference.modelscope.cn/v1"
# AI_MODEL = "deepseek-ai/DeepSeek-V3"
