# Railway配置文件 - 最小化配置
# https://docs.railway.app/reference/config-file

[build]
builder = "nixpacks"

# 使用Railway默认部署设置
# [deploy]
# 默认的重启策略和健康检查

# 以下环境变量需要在Railway控制台中手动设置
# NODE_ENV = "production"
# AI_API_KEY = "ms-150d583e-ed00-46d3-ab35-570f03555599"
# AI_BASE_URL = "https://api-inference.modelscope.cn/v1"
# AI_MODEL = "deepseek-ai/DeepSeek-V3"
