# Railway配置文件
# https://docs.railway.app/reference/config-file

[build]
builder = "nixpacks"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
# 健康检查配置
healthcheckPath = "/health"
healthcheckTimeout = 30

[env]
NODE_ENV = "production"

# 以下环境变量需要在Railway控制台中手动设置
# AI_API_KEY = "ms-150d583e-ed00-46d3-ab35-570f03555599"
# AI_BASE_URL = "https://api-inference.modelscope.cn/v1"
# AI_MODEL = "deepseek-ai/DeepSeek-V3"
